### ISSUE TITLE
Not possible to set Premain-Class value in MANIFEST.MF

### ISSUE THREAD

**Issue by borisbsu** [SonarSource/sonar-packaging-maven-plugin#17]
The current version of plugin doesn't allow to set Premain-Class value in MANIFEST.MF which is required in case of creation core extension for Sonarqube 9.x.

It would be great to have a possibility to add any own custom entries into MANIFEST.MF

**Comment by lukasz-jarocki-sonarsource** [comment]
Hi @borisbsu,

thank you for the feedback. I've created a ticket to track this issue. https://jira.sonarsource.com/browse/SONAR-16111
