### ISSUE TITLE
provide opton to skip WARNING for provided packages

### ISSUE THREAD

**Issue by romani** [SonarSource/sonar-packaging-maven-plugin#6]
Reporting of WARNING is required only to attract attention of engineer to make a fix.
Permanent reporting of WARNING does not do any good to build stability.

please provide an configuration property to skip such warnings. 

During build there are warnings :
```
[WARNING] com.google.guava:guava:jar:10.0.1:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.slf4j:jcl-over-slf4j:jar:1.7.5:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] com.google.code.findbugs:jsr305:jar:1.3.9:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.slf4j:slf4j-api:jar:1.7.5:compile is provided by SonarQube plugin API and will not be packaged in your plugin
[WARNING] org.picocontainer:picocontainer:jar:2.14.1:compile is provided by SonarQube plugin API and will not be packaged in your plugin
```

Related code: https://github.com/SonarSource/sonar-packaging-maven-plugin/blob/master/src/main/java/org/sonarsource/pluginpackaging/SonarPluginMojo.java#L216

**Comment by henryju** [comment]
We are deprecating the ability to package libraries as jar. You should use shading instead. Please see https://jira.sonarsource.com/browse/PACKMP-13
