### ISSUE TITLE
Update plugin for 5.2 class loading model

### ISSUE THREAD

**Issue by marschall** [SonarSource/sonar-packaging-maven-plugin#9]
The plugin currently assumes a pre SonarQube 5.2 class loading environment where all sorts of stuff is provided by SonarQube. Starting with SonarQube 5.2 this is no longer true [1]. As a consequence if your plugin depends on Guava there is no way to get it running on SonarQube 5.6 as the plugin stubbornly refuses to package Guava because it assumes it will still be provided by SonarQube. This is no longer true so you will get `NoClassDefFoundError`s and SonarQube will refuse to start.

 [1] https://docs.sonarqube.org/display/DEV/Build+Plugin

**Comment by henryju** [comment]
We are deprecating the ability to bundle dependencies as libraries. You should use shading instead. See https://jira.sonarsource.com/browse/PACKMP-13

**Comment by marschall** [comment]
@henryju are there alternatives to shading? Shading in practice is quite hard because:

- you have to unsign signed JARs
- you have to correctly transform everything that uses `META-INF/services`
- you have to know which additional resources you have to transform like `spring.factories`
- you have to know which manifest headers are important that you need to update like `Multi-Release`
- correctly transform preserve all license files to make sure you're still compliant with all licenses

**Comment by henryju** [comment]
@marschall thanks for the feedback, I will discuss that internally. Just for clarification, are you talking about hypothetical issues, or are you aware of plugins that would be in one of those situation.

**Comment by marschall** [comment]
@henryju these are just general experiences I had with shading over the years. It has been quite some time form me and I don't know the current situation with plugins.
